New spells
Unlimited-Pasta-Pass/Hush-game pull request #106
Opened 2021-11-27 19:14 UTC by daniela-venuta

2021-11-27 22:24 UTC, redknight990 approved these changes
Looks Good! Nice rework to accommodate multiple spell types!

2021-11-27 22:50 UTC, arejayelle reviewed
Fireball light seems to go at a 90ish degree angle from where the fireball actually is + there are bugs w/ the invisiblity spell (as discussed)

2021-11-27 23:19 UTC, arejayelle approved these changes
Would prefer to have OnStart instead of onAwake for the spell initialization but since this is gonna be replaced SOON ish, it's fine. 

Don't forget to make an issue for the fireball bug

2021-11-27 23:36 UTC, daniela-venuta commented
> Fireball light seems to go at a 90ish degree angle from where the fireball actually is + there are bugs w/ the invisiblity spell (as discussed)

Created a bug for fireball and invisibility has been fixed

2021-11-28 00:03 UTC, po-trottier requested changes
Good job! Few small changes

2021-11-28 00:03 UTC, po-trottier commented on Hush/Assets/Scripts/Weapon/StunSpell.cs
> +        }
```suggestion
```

2021-11-28 00:03 UTC, po-trottier commented on Hush/Assets/Scripts/Weapon/Enums/StunCollision.cs
> +        void OnParticleCollision(GameObject other)
Might wanna use a SphereCast in the Spell Prefab to do that

2021-11-28 00:04 UTC, po-trottier commented
> > Fireball light seems to go at a 90ish degree angle from where the fireball actually is + there are bugs w/ the invisiblity spell (as discussed)
> 
> Created a bug for fireball and invisibility has been fixed

Fireball bug was already fixed by @redknight990 in his PR

2021-11-28 02:43 UTC, po-trottier approved these changes
Gucci

2021-11-28 02:47 UTC, po-trottier approved these changes
Good again

2021-11-28 02:47 UTC, merged