Add Smoke Effect on Enemy Spawn From Relic
Unlimited-Pasta-Pass/Hush-game pull request #111
Opened 2021-11-28 08:18 UTC by daniela-venuta

Closes #74

Adds smoke effect and a short delay before enemies spawn to give the player a warning

2021-11-28 08:21 UTC, po-trottier commented on Hush/Assets/Scripts/Relics/RelicEnemySpawner.cs
> +         yield return new WaitForSeconds(.3f);
delay should be SerializeField

2021-11-28 08:22 UTC, po-trottier commented on Hush/Assets/Scripts/Relics/RelicEnemySpawner.cs
> +         var target = GameObject.FindWithTag(Tags.Relic);
Don't need to find the target every time you spawn an enemy... should either be a serializeField or Find 1x and then set this

2021-11-28 08:22 UTC, po-trottier requested changes
2 minor changes

2021-11-28 15:26 UTC, emilie-martin approved these changes
navmesh is broken but that's gonna be taken care of in another PR (#112 ) so you're good to go for me; it looks good! ☁️

2021-11-29 05:08 UTC, po-trottier approved these changes
![image](https://user-images.githubusercontent.com/41876093/143812138-78cb3035-0333-4b65-9fed-b26d5fc5b54d.png)

2021-11-29 16:57 UTC, arejayelle approved these changes
works fine.

### minor
The smoke effect would look better if it was much shorter (since the enemies are popping into the scene instantly) and possibly make it circular like it's radiating on the floor off of them.  

Something like this: 
https://user-images.githubusercontent.com/35614138/143910210-f3bf7acf-de82-4663-811a-aa9e3e0a7db1.mp4

2021-11-29 19:02 UTC, daniela-venuta commented
> works fine.
> 
> ### minor
> The smoke effect would look better if it was much shorter (since the enemies are popping into the scene instantly) and possibly make it circular like it's radiating on the floor off of them.
> 
> Something like this: https://user-images.githubusercontent.com/35614138/143910210-f3bf7acf-de82-4663-811a-aa9e3e0a7db1.mp4

I'm gonna merge this for now as the duration is a serialized field so we can change this in the editor pretty easily. Can make more circular later

2021-11-29 19:03 UTC, merged